language: ruby
cache: bundler
script:
  - bundle exec rubocop
  - bundle exec rake
<<<<<<< Updated upstream
=======

gemfile:
  - gemfiles/activerecord_4.2.0.gemfile
  - gemfiles/activerecord_5.0.2.gemfile
  - gemfiles/activerecord_5.1.0.gemfile
  - gemfiles/activerecord_5.2.2.gemfile
  - gemfiles/activerecord_6.0.0.gemfile
>>>>>>> Stashed changes
